language: node_js
node_js: "8.11.1"
script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: 'npm run coverage'